version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: time-report-api
    container_name: time-report-api
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ConexionBD=Server=sqlserver,1433;Database=ISC_TimeReport_prod;User=app_backend;Password=Ayy@8#kV50wPp@tR11m;MultipleActiveResultSets=true;Trust Server Certificate=true
      - JWT__JWTSecretKey=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - Cors__AllowedOrigins=http://localhost:4200,https://localhost:4200,https://app.timereport.integritysolutions.com.ec,http://147.93.181.147:4200/,http://147.93.181.147:4200
      - EmailSettings__SmtpServer=smtp.hostinger.com
      - EmailSettings__Port=465
      - EmailSettings__SenderName=TimeReport App
      - EmailSettings__SenderEmail=siaft@siaft.net
      - EmailSettings__Username=siaft@siaft.net
      - EmailSettings__Password=Vrocoli23_
      - Infrastructure__InventoryAPIUrlBase=https://api.inv.dokploy.integritysolutions.com.ec
      - Infrastructure__InventoryAuthUrlBase=https://auth.inv.dokploy.integritysolutions.com.ec
      - InventoryCredentials__Email=kerly.jimenez@integritysolutions.com.ec
      - InventoryCredentials__Password=Password2@
    depends_on:
      - sqlserver
    networks:
      - backend-net
